version: '3.3'
services:
    portainer-ce:
        container_name: portainer
        ports:
            - 9443:9443
            - 9000:9000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - data:/data
        restart: always
        image: portainer/portainer-ce:latest
 
volumes:
  data:
